---
title: "Untitled"
author: "erin"
date: "1/23/2019"
output: html_document
---

```{r}
"symmetric_collision"
"A follows B"
"B follows A"
"A hits B"
"B hits A"

"s1_enumeration_AmovedB_3velocities_s0.53.js"
```

```{r}
parse_label = function(label, var, val) {
  label = strsplit(label, "probability of 'A moved B': ")[[1]][[2]]
  s = strsplit(label, "params: \\{\"probs\":\\[")
  endorsement = num(s[[1]][[1]])
  label = s[[1]][[2]]
  probs = strsplit(strsplit(label, "\\]")[[1]][[1]], ",")[[1]] %>% num()
  new_var = c("endorsement", "ww", "wh", "hw", "hh")
  new_val = c(endorsement, probs)
  data.frame(var=c(var, new_var), val=c(val, new_val)) %>%
    return()
}
  results_dir = function(f) {
    return(paste("~/Projects/causal_simulations/results/", f, sep=""))
  }
read_explanations_rs = function(n) {
  f = results_dir(paste("s1_enumeration_AmovedB_", n, "velocities_s0.53.js", sep=""))
  d = read_file(f) %>%
    substring(14) %>%
    fromJSON()
  df = d$world$A %>%
    mutate(ball="A",
           label=d$label,
           id=1:length(ball)) %>%
    rbind(d$world$B %>%
            mutate(ball="B",
                   label=d$label,
                   id=1:length(ball))) %>%
    gather("var", "val", c(velocity, position)) %>%
    unite("var", ball, var)
  df %>% group_by(id) %>%
    do(parse_label(.$label, .$var, .$val)) %>%
    ungroup() %>%
    spread(var, val) %>%
    mutate(n = n) %>%
    return()
}
```

```{r}
df = do.call(rbind, lapply(c(3,5,7,11), read_explanations_rs)) %>%
  mutate(n = factor(n))
```

```{r}
get_world_name = function(a, b, c, d) {
  if (a==-1 & b==-1) {
    return("B follows A")
  } else if (a==1 & b==1) {
    return("A follows B")
  } else if (a==1 & b==0) {
    return("A hits B")
  } else if (a==0 & b==-1) {
    return("B hits A")
  } else if (a==1 & b==-1) {
    return("symmetric collision")
  } else {
    return("NA")
  }
}
df = df %>%
  mutate(name = mapply(get_world_name, A_velocity, B_velocity, A_position, B_position))
```


```{r, fig.width=5, fig.height=1.5}
df %>%
  ggplot(aes(x=n, y=endorsement#, fill=name, colour=name
             )) +
  geom_bar(stat="identity", alpha=1/2) +
  scale_fill_brewer(type="qual", palette = 6) +
  scale_colour_brewer(type="qual", palette = 6) +
  facet_grid(~name) +
  ylim(0, 1)
ggsave(results_dir("endorsement_by_velocity.png"), width=10, height=3)
```


```{r, fig.width=5, fig.height=3}
df %>%
  filter(n==3) %>%
  ggplot(aes(x=name, y=endorsement#, fill=name, colour=name
             )) +
  geom_bar(stat="identity", alpha=1/2) +
  scale_fill_brewer(type="qual", palette = 6) +
  scale_colour_brewer(type="qual", palette = 6) +
  # facet_grid(~name) +
  ylim(0, 1)
ggsave(results_dir("endorsement_by_world_n3.png"), width=5, height=3)
```


```{r, fig.width=5, fig.height=3}
df %>%
  gather("params", "prob", c(ww, wh, hw, hh)) %>%
  ggplot(aes(x=params, y=prob#, fill=params, colour=params
             )) +
  geom_bar(stat="identity", position="dodge", alpha=1/2) +
  scale_fill_brewer(type="qual", palette = 6) +
  scale_colour_brewer(type="qual", palette = 6) +
  facet_grid(n~name) +
  ylim(0, 1)
ggsave(results_dir("params_by_velocity.png"), width=10, height=6)
```



```{r}
"symmetric_collision"
"A follows B"
"B follows A"
"A hits B"
"B hits A"

"s1_enumeration_AmovedB_3velocities_s0.53.js"
```

```{r}
parse_label = function(label, var, val) {
  label = strsplit(label, "probability of 'A moved B': ")[[1]][[2]]
  s = strsplit(label, "params: \\{\"probs\":\\[")
  endorsement = num(s[[1]][[1]])
  label = s[[1]][[2]]
  probs = strsplit(strsplit(label, "\\]")[[1]][[1]], ",")[[1]] %>% num()
  new_var = c("endorsement", "ww", "wh", "hw", "hh")
  new_val = c(endorsement, probs)
  data.frame(var=c(var, new_var), val=c(val, new_val)) %>%
    return()
}
  results_dir = function(f) {
    return(paste("~/Projects/causal_simulations/results/", f, sep=""))
  }
read_explanations_rs = function(n) {
  f = results_dir(paste("s1_enumeration_AmovedB__unlifted_", n, "velocities_s0.53.js", sep=""))
  d = read_file(f) %>%
    substring(14) %>%
    fromJSON()
  df = d$world$A %>%
    mutate(ball="A",
           label=d$label,
           id=1:length(ball)) %>%
    rbind(d$world$B %>%
            mutate(ball="B",
                   label=d$label,
                   id=1:length(ball))) %>%
    gather("var", "val", c(velocity, position)) %>%
    unite("var", ball, var)
  df %>% group_by(id) %>%
    do(parse_label(.$label, .$var, .$val)) %>%
    ungroup() %>%
    spread(var, val) %>%
    mutate(n = n) %>%
    return()
}
```

```{r}
df = do.call(rbind, lapply(c(3,5,7,11), read_explanations_rs)) %>%
  mutate(n = factor(n))
```

```{r}
get_world_name = function(a, b, c, d) {
  if (a==-1 & b==-1) {
    return("B follows A")
  } else if (a==1 & b==1) {
    return("A follows B")
  } else if (a==1 & b==0) {
    return("A hits B")
  } else if (a==0 & b==-1) {
    return("B hits A")
  } else if (a==1 & b==-1) {
    return("symmetric collision")
  } else {
    return("NA")
  }
}
df = df %>%
  mutate(name = mapply(get_world_name, A_velocity, B_velocity, A_position, B_position))
```


```{r, fig.width=5, fig.height=1.5}
df %>%
  ggplot(aes(x=n, y=endorsement#, fill=name, colour=name
             )) +
  geom_bar(stat="identity", alpha=1/2) +
  scale_fill_brewer(type="qual", palette = 6) +
  scale_colour_brewer(type="qual", palette = 6) +
  facet_grid(~name) +
  ylim(0, 1)
ggsave(results_dir("endorsement_by_velocity.png"), width=10, height=3)
```



```{r, fig.width=5, fig.height=3}
df %>%
  gather("params", "prob", c(ww, wh, hw, hh)) %>%
  ggplot(aes(x=params, y=prob#, fill=params, colour=params
             )) +
  geom_bar(stat="identity", position="dodge", alpha=1/2) +
  scale_fill_brewer(type="qual", palette = 6) +
  scale_colour_brewer(type="qual", palette = 6) +
  facet_grid(n~name) +
  ylim(0, 1)
ggsave(results_dir("params_by_velocity.png"), width=10, height=6)
```
