---
title: "Explanations AB 1D"
author: "Erin Bennett"
header-includes:
   - \usepackage{tikz}
   - \usetikzlibrary{bayesnet}
output: html_document
---

```{r global_options, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = F, warning = F, cache = F, message = F,
                      sanitiz = F, fig.width = 5, fig.height = 3)
```

```{r load (and reformat) data}
source("../utils.R")
```

```{r}
plot_velocities = function(n) {
  f = results_dir(paste("l0_AmovedB_", n, "velocities_s0.53.js", sep=""))
  d = read_file(f) %>%
    substring(14) %>%
    fromJSON()
  df = d$world$A %>%
    mutate(ball="A",
           label=d$label,
           id=1:length(ball)) %>%
    rbind(d$world$B %>%
            mutate(ball="B",
                   label=d$label,
                   id=1:length(ball))) %>%
    gather("var", "val", c(velocity, position)) %>%
    rename(prob = label)
  # select only the worlds where A is on the left.
  worlds_to_graph = df %>%
    unite("var", ball, var) %>%
    spread(var, val) %>%
    filter(A_position==0) %>%
    # and renormalize
    mutate(prob = prob/sum(prob)) %>%
    select(A_velocity, B_velocity, prob) %>%
    rbind(data.frame(A_velocity=0, B_velocity=0, prob=0))
  worlds_to_graph %>%
    fill_df(c("A_velocity", "B_velocity")) %>%
    ggplot() +
    aes(x=A_velocity, y=B_velocity, fill=prob) +
    geom_tile() +
    geom_text(aes(label=round(prob, 3)))
}
```

```{r}
plot_velocities(3)
plot_velocities(5)
plot_velocities(7)
```

```{r}
n=11
  f = results_dir(paste("l0_AmovedB_", n, "velocities_s0.53.js", sep=""))
  d = read_file(f) %>%
    substring(14) %>%
    fromJSON()
  df = d$world$A %>%
    mutate(ball="A",
           label=d$label,
           id=1:length(ball)) %>%
    rbind(d$world$B %>%
            mutate(ball="B",
                   label=d$label,
                   id=1:length(ball))) %>%
    gather("var", "val", c(velocity, position)) %>%
    rename(prob = label)
  # select only the worlds where A is on the left.
  worlds_to_graph = df %>%
    unite("var", ball, var) %>%
    spread(var, val) %>%
    filter(A_position==0) %>%
    # and renormalize
    mutate(prob = prob/sum(prob)) %>%
    select(A_velocity, B_velocity, prob) %>%
    rbind(data.frame(A_velocity=0, B_velocity=0, prob=0))
 worlds_to_graph= worlds_to_graph %>%
    rename(A = A_velocity, B = B_velocity)
```

```{r}
worlds_to_graph %>% filter(A > B, A < 0)
```


